export const headingTexts: string[] = [
  "WEB DEVELOPMENT",  
  "SHOPIFY DEVELOPMENT",  
  "WORDPRESS DEVELOPMENT",  
  "SOFTWARE DEVELOPMENT",  
  "AI DEVELOPMENT",  
  "DIGITAL MARKETING",  
  "ERP DEVELOPMENT",  
  "CYBER SECURITY SERVICES"
];
